server:
  port: 9991
spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 47.113.101.241:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"
